name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 0-19 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"

      - run: pipenv install

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          workflow_conclusion: success
          name: session-artifact
          path: ./

      - name: Run main.py
        run: pipenv run python main.py
        env:
          TELEGRAM_BOT_TOKEN: "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"
          c_user: "${{ secrets.C_USER }}"
          xs: "${{ secrets.XS }}"
          FACEBOOK_GROUP_ID: "${{ secrets.GROUP_ID }}"
          LOOKBACK: 30

      - name: Upload run artifact
        uses: actions/upload-artifact@v2
        with:
          name: session-artifact
          path: session.txt
