name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0-16/3 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          workflow_conclusion: success
          name: session-artifact
          path: ./

      - name: Run main.py
        run: pipenv run python main.py
        env:
          TELEGRAM_BOT_TOKEN: "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"
          c_user: "${{ secrets.C_USER }}"
          datr: "${{ secrets.DATR }}"
          fr: "${{ secrets.FR }}"
          sb: "${{ secrets.SB }}"
          xs: "${{ secrets.XS }}"
          GROUP_ID: "${{ secrets.GROUP_ID }}"

      - name: Upload run artifact
        uses: actions/upload-artifact@v2
        with:
          name: session-artifact
          path: session.txt
